### ISSUE TITLE
ValueError: `X` and `y` both have indexes, but they do not match.

### ISSUE THREAD

**Issue by simonprovost** [Alex-Lekov/AutoML_Alex#37]
Hi **Alex**,

Amazing AutoML contribution. Was interested in trying your system but got an error. Even on your colab examples.

**Error**: ValueError: `X` and `y` both have indexes, but they do not match.

**Step to reproduce**: Simply run the following colab --> https://colab.research.google.com/github/Alex-Lekov/AutoML_Alex/blob/master/examples/01_Quick_Start.ipynb#scrollTo=YSBt7jh3fB34

**Screenshot of the error**: <img width="972" alt="Screenshot 2022-06-26 at 02 56 22" src="https://user-images.githubusercontent.com/32747568/175795024-dbde7af8-ef75-40db-aa73-53e832519523.png">

**Comment by Alex-Lekov** [comment]
fix in new version 2023.3.10
